# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: 'Dmitry S. Kulyabov'
# Website URL
baseURL: 'https://yamadharma.github.io/'
copyright: '&copy; {year} Dmitry S. Kulyabov'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: true
removePathAccents: true

languages:
  ru:
    params:
      date_format: "2006-01-02"
      address_format: zh

############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: post/**
    editable: false
    reading_time: true
    commentable: false
    show_related: true
    show_breadcrumb: true
    share: false
    backlinks: true
    header:
      navbar:
        enable: true
  - _target:
      path: teaching/**
    editable: false
    reading_time: true
    commentable: false
    show_related: true
    show_breadcrumb: true
    share: false
    backlinks: true
    invert_pager: false
    header:
      navbar:
        enable: true

############################
## ADVANCED
############################

build:
  writeStats: true

enableGitInfo: false
summaryLength: 30

pagination:
  pagerSize: 20

enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

permalinks:
  post: '/post/:year/:month/:day/:slug'
  authors: '/author/:slug/'
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'

disableAliases: true

outputs:
  home: [HTML, RSS, headers, redirects, backlinks, WebAppManifest]
  page: [HTML, RSS]
  rss: [RSS]
  section: [HTML, RSS]
  taxonomy: [HTML, RSS]
  term: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 85
  anchor: smart
timeout: 600000

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

markup:
  _merge: deep
  defaultMarkdownHandler: goldmark
  goldmark:
    renderHooks:
      link:
        # Process backlinks hook
        enableDefault: true
    renderer:
      # Render HTML in Markdown
      unsafe: true
    parser:
      # Support Latex math
      attribute:
        block: true
        title: true
    extensions:
      # Support Latex math
      passthrough:
        enable: true
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
            - - $
              - $
      extras:
        # Enable subscript, superscript, and highlighting with ~,^, and == wrappers
        insert:
          enable: false
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
  highlight:
    # Enable code highlighting
    codeFences: true
    noHl: false
    lineNumbersInTable: false
    noClasses: false
    guessSyntax: true
    anchorLineNos: true
    lineNoStart: 1
    lineNos: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
minify:
  minifyOutput: true
  tdewolff:
    html:
      keepComments: true
      keepSpecialComments: true
sitemap:
  changefreq: weekly
module:
  hugoVersion:
    min: '0.126.0'
    extended: true
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-analytics
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
security:
  funcs:
    getenv:
      # Allow HUGO_ and HUGO_BLOX_ vars
      - ^HUGO_
      # Allow continuous integration vars
      - ^CI$
outputFormats:
  backlinks:
    mediaType: application/json
    baseName: backlinks
    isPlainText: true
    notAlternative: true
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
params:
  locale:
    date_format: '2006-01-02'
    time_format: '15:04'
    address_format: zh
related:
  threshold: 80.0
  includeNewer: true
  toLower: true
  indices:
    - name: title
      weight: 60.0
    - name: summary
      weight: 50.0
    - name: tags
      weight: 80.0
    - name: categories
      weight: 70.0
    - name: authors
      weight: 20.0

enableRobotsTXT: true
canonifyURLs: true

mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
    
