# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: 'Dmitry S. Kulyabov' # Website name
baseURL: 'https://yamadharma.github.io/' # Website URL
copyright: '&copy; {year} Dmitry S. Kulyabov'

############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /post/**
    editable: false
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true
    share: true
    header:
      navbar:
        enable: true
  - _target:
      path: /course/**
    editable: false
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true
    share: true
    header:
      navbar:
        enable: true


############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: true
removePathAccents: true

languages:
  ru:
    params:
      date_format: "2006-01-02"
      address_format: zh

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 20
enableEmoji: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

permalinks:
  post: '/post/:year/:month/:day/:slug'
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'

disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

markup:
  _merge: deep
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    anchorLineNos: true
    lineNoStart: 1
    lineNos: false
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

related:
  threshold: 80.0
  includeNewer: true
  toLower: true
  indices:
    - name: title
      weight: 60.0
    - name: summary
      weight: 50.0
    - name: tags
      weight: 80.0
    - name: categories
      weight: 70.0
    - name: authors
      weight: 20.0

security:
  _merge: deep
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_

sitemap:
  _merge: deep

enableRobotsTXT: true
canonifyURLs: true

mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest

outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest


