# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language

ru:
  languageCode: ru-ru
  contentDir: content/ru
  title: Д. С. Кулябов  
  menu:
    main:
      - name: Обо мне
        url: '#about'
        weight: 10
      - name: Блог
        url: '#posts'
        weight: 20
      - name: Проекты
        url: '#projects'
        weight: 30
      - name: Публикации
        url: '#featured'
        weight: 40
      - name: Курсы
        url: course/
        weight: 50
      - name: Контакты
        url: '#contact'
        weight: 60
en:
  languageCode: en-us
  contentDir: content/en
  title: Dmitry S. Kulyabov
